from __future__ import annotations

from typing import Any

from markdown_it import MarkdownIt

from app.security_scan.reporting.markdown_report import render_markdown_report


def render_html_report(
    payload: dict[str, Any],
    charts_html: str | None = None,
) -> str:
    markdown_report = render_markdown_report(payload)
    renderer = MarkdownIt("commonmark").enable("table")
    body_html = renderer.render(markdown_report)

    if charts_html:
        charts_section = (
            "\n<section class=\"charts\">\n"
            "<h2>Aggregate Timeseries</h2>\n"
            f"{charts_html}\n"
            "</section>\n"
        )
        h1_end_index = body_html.find("</h1>")
        if h1_end_index != -1:
            insert_pos = h1_end_index + 5
            body_html = body_html[:insert_pos] + charts_section + body_html[insert_pos:]
        else:
            body_html = charts_section + body_html

    return (
        "<!doctype html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\" />\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
        "  <title>Security Scan Report</title>\n"
        "  <style>\n"
        "    :root {\n"
        "      color-scheme: light;\n"
        "      --bg: #ffffff;\n"
        "      --text: #0f172a;\n"
        "      --muted: #475569;\n"
        "      --surface: #ffffff;\n"
        "      --surface-muted: #f8fafc;\n"
        "      --border: #cbd5e1;\n"
        "      --border-strong: #94a3b8;\n"
        "      --code-bg: #f1f5f9;\n"
        "      --table-header-bg: #b7cadd;\n"
        "      /*\n"
        "       * High-contrast, colorblind-friendly striping:\n"
        "       * - Row colors are non-white so the pattern reads immediately.\n"
        "       * - Column striping is a neutral overlay.\n"
        "       * - Intersections use a lighter overlay so they don't become disproportionately dark.\n"
        "       */\n"
        "      /* Cool / warm row zebra to improve readability (blue + sepia). */\n"
        "      --table-row-odd: #e1ebf6;\n"
        "      --table-row-even: #e3d3ab;\n"
        "      --table-col-overlay: rgba(15, 23, 42, 0.10);\n"
        "      --table-col-overlay-cross: rgba(15, 23, 42, 0.07);\n"
        "      --table-hover: rgba(59, 130, 246, 0.10);\n"
        "    }\n"
        "    body {\n"
        "      margin: 24px;\n"
        "      font-family: ui-sans-serif, system-ui, -apple-system, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif;\n"
        "      font-size: 16px;\n"
        "      line-height: 1.45;\n"
        "      color: var(--text);\n"
        "      background: var(--bg);\n"
        "    }\n"
        "    .report {\n"
        "      max-width: 1100px;\n"
        "      margin: 0 auto;\n"
        "    }\n"
        "    h1, h2, h3 {\n"
        "      margin-top: 1.4rem;\n"
        "      letter-spacing: -0.01em;\n"
        "    }\n"
        "    h1 {\n"
        "      margin-top: 0;\n"
        "    }\n"
        "    table {\n"
        "      border-collapse: separate;\n"
        "      border-spacing: 0;\n"
        "      width: 100%;\n"
        "      margin-bottom: 1.5rem;\n"
        "      font-size: 0.95rem;\n"
        "      background: var(--surface);\n"
        "      border: 1px solid var(--border-strong);\n"
        "      border-radius: 10px;\n"
        "      overflow: hidden;\n"
        "      box-shadow: 0 1px 0 rgba(15, 23, 42, 0.04);\n"
        "    }\n"
        "    th, td {\n"
        "      padding: 10px 12px;\n"
        "      text-align: left;\n"
        "      white-space: normal;\n"
        "      overflow-wrap: anywhere;\n"
        "      word-break: break-word;\n"
        "      vertical-align: top;\n"
        "      border-right: 1px solid var(--border);\n"
        "      border-bottom: 1px solid var(--border);\n"
        "    }\n"
        "    thead th {\n"
        "      background: var(--table-header-bg);\n"
        "      font-weight: 700;\n"
        "      border-bottom: 1px solid var(--border-strong);\n"
        "    }\n"
        "    thead th:nth-child(even) {\n"
        "      background-image: linear-gradient(var(--table-col-overlay), var(--table-col-overlay));\n"
        "    }\n"
        "    th:last-child, td:last-child {\n"
        "      border-right: none;\n"
        "    }\n"
        "    tbody tr:last-child td {\n"
        "      border-bottom: none;\n"
        "    }\n"
        "    tbody tr:nth-child(odd) td {\n"
        "      background-color: var(--table-row-odd) !important;\n"
        "    }\n"
        "    tbody tr:nth-child(even) td {\n"
        "      background-color: var(--table-row-even) !important;\n"
        "    }\n"
        "    tbody td:nth-child(even) {\n"
        "      background-image: linear-gradient(var(--table-col-overlay), var(--table-col-overlay)) !important;\n"
        "    }\n"
        "    tbody tr:nth-child(even) td:nth-child(even) {\n"
        "      background-image: linear-gradient(var(--table-col-overlay-cross), var(--table-col-overlay-cross)) !important;\n"
        "    }\n"
        "    tbody tr:hover td {\n"
        "      box-shadow: inset 0 0 0 9999px var(--table-hover);\n"
        "    }\n"
        "    code {\n"
        "      background: var(--code-bg);\n"
        "      padding: 0 4px;\n"
        "      border-radius: 4px;\n"
        "      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
        "      font-size: 0.92em;\n"
        "    }\n"
        "    pre {\n"
        "      background: var(--code-bg);\n"
        "      padding: 12px;\n"
        "      border-radius: 6px;\n"
        "      overflow-x: auto;\n"
        "      border: 1px solid var(--border);\n"
        "    }\n"
        "    pre code {\n"
        "      padding: 0;\n"
        "      border-radius: 0;\n"
        "      background: transparent;\n"
        "    }\n"
        "    .charts {\n"
        "      margin: 2rem 0;\n"
        "    }\n"
        "    .chart-block {\n"
        "      margin-top: 1.5rem;\n"
        "    }\n"
        "    .chart-block h3 {\n"
        "      margin: 0 0 0.75rem;\n"
        "    }\n"
        "  </style>\n"
        "</head>\n"
        "<body>\n"
        "  <article class=\"report\">\n"
        f"{body_html}\n"
        "  </article>\n"
        "</body>\n"
        "</html>\n"
    )
